[package]
name = "engine-types"
version = "0.1.0"
authors = []
edition = "2021"
description = ""
documentation = ""
readme = false
homepage = ""
repository = ""
license = ""
publish = false
autobenches = false

[dependencies]
hex = { version = "0.4", default-features = false, features = ["alloc"] }
primitive-types = { version = "0.10.0", default-features = false, features = ["rlp"] }
protobuf = "2.27.1"

[dev-dependencies]
rand = "0.7.3"

[features]
default = ["std"]
std = ["primitive-types/std"]